# Generated by Django 5.2.10 on 2026-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('date_created', models.DateField(verbose_name='Дата заказа')),
                ('date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('receive_code', models.IntegerField(verbose_name='Код для получения')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Завершен', 'Завершен')], default='Новый', max_length=50, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес пункта выдачи')),
            ],
        ),
    ]
