# Generated by Django 5.2.10 on 2026-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('supplier', models.CharField(max_length=255, verbose_name='Поставщик')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('category', models.CharField(max_length=255, verbose_name='Категория товара')),
                ('discount', models.IntegerField(default=0, verbose_name='Действующая скидка (%)')),
                ('stock', models.IntegerField(default=0, verbose_name='Кол-во на складе')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
            ],
        ),
    ]
